version: '3.8'

services:
  api:
    container_name: api_test
    build: './api'
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
      POSTGRES_HOST: db
    ports:
      - 3000:3000
    volumes:
      - ./api/src:/usr/api/src
  db:
    container_name: dev_store  
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
    ports:
      - 5432:5432